### ISSUE TITLE
help request of command getState()

### ISSUE THREAD

**Issue by 889laurent** [duncan3dc/sonos#10]
the result of command getState() is a number (202 for playing) and in your exemple it use thise code
with alphanumeric "Controller::STATE_PLAYING"
if ($controller->getState() !== Controller::STATE_PLAYING) {
         $controller->play();

please help me about this

**Comment by duncan3dc** [comment]
Controller::STATE_PLAYING is a [class constant](http://php.net/manual/en/language.oop5.constants.php) which [represents the number 202](https://github.com/duncan3dc/sonos/blob/7cf1ae34800dcd2446a4da09e747d7fd03c6e231/src/Controller.php#L24).

-----

We use this because this:
```php
if ($state === Controller::STATE_PLAYING) {
```
is a lot more readable than:
```php
if ($state === 202) {
```

**Comment by 889laurent** [comment]
thanks i understand now
