### ISSUE TITLE
Model types: new Sonos Amp

### ISSUE THREAD

**Issue by kvanisterdael** [duncan3dc/sonos#105]
Another unrecognized device: the new AMP. I couldn't find the device code yet.

But I was wondering if we couldn't eliminate the isSpeaker method? All devices are speakers in the current Sonos range, so what's the added value?
With the current implementation, we need to update every time a new model comes out...

**Comment by duncan3dc** [comment]
Hi @kvanisterdael, I'm afraid that's not the case, there are some devices in the current range that are not speakers (eg the Bridge), and without `isSpeaker()` the library will throw an exception when dealing with non-speakers.

So the approach taken is that new devices have to be added, because at least the library still works, and new non-speaker devices don't prevent users from using this library at all.

You have the AMP connected to your network? If so, please [enable logging](http://duncan3dc.github.io/sonos/setup/logging/) and run some code (anything that uses `getSpeakers()` should be fine) then paste the output here or in a gist, it should contain the model number needed to add support

**Comment by duncan3dc** [comment]
Fixed in 2.2.1
