### ISSUE TITLE
Delete long lived cache

### ISSUE THREAD

**Issue by patrickharris** [duncan3dc/sonos#16]
I can't see a way to delete the long-lived cache. If there is no way, can we add to the Network:

    public function deleteCache() {
        $cache = $this->cache;
        $cache->deleteAll();
    }

**Comment by duncan3dc** [comment]
The way to clear the cache is to pass in your own Cache instance, this is the power of dependency injection, you are in complete control of the cache. So rather than having to add a bunch of Cache methods to the Network class, we just accept a cache instance that you can do anything you want with:

```php
$cache = new \Doctrine\Common\Cache\FilesystemCache("/tmp/sonos-cache");
$sonos = new \duncan3dc\Sonos\Network($cache);

# Clear the cache when the user requests
if (isset($_REQUEST["clear-cache"])) {
    $cache->deleteAll();
}
```

```php
# Use a different cache on each day
$cache = new \Doctrine\Common\Cache\FilesystemCache("/tmp/sonos-cache_" . date("Y-m-d"));
$sonos = new \duncan3dc\Sonos\Network($cache);
```

I would always recommend passing in a Cache instance, so you can manage it how your Sonos network requires. Using the default cache is simply a configuration convenience to get up and running quickly

**Comment by Rello** [comment]
Hello @duncan3dc ,

I am no sure about the 1.9 usage as the docu handles 2.0.
2.0 mentions that a cache collector specifically needs to be set up an provided.

what about the 1.9 as mentioned above? what is the default mode there?

**Comment by duncan3dc** [comment]
Hi @rello, as mentioned above, the default in 1.9 is a long lived cache, however I advise you not to rely on the default, and instead specify your own cache settings

**Comment by Rello** [comment]
Hello, 
that was quick :-)

ok, thank you. I just checked the Doctrine/Common/Cache folder. I will test with other types.
any recommendation with least dependencies (e.g. Memcache needs to be provided by the server)
